# Aula 15 - Algoritmos e Estrutura de Dados 
## Exercícios sobre Numpy

## Fácil

⚫1- Importe numpy como ‘np’ e imprima o número da versão.

In [1]:
import numpy as np
print(np.__version__)

1.26.4


⚫2- Crie uma matriz 1D com números de 0 a 9

In [2]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


⚫3- Crie uma matriz booleana numpy 3×3 com ‘True’

In [3]:
import numpy as np
print(np.full((3, 3), True, dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
print(np.ones((3, 3), dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


⚫4- Extraia todos os números ímpares de ‘arr’

In [5]:
import numpy as np
arr = np.arange(0, 10) 
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

⚫5- Substitua todos os números ímpares arr por -1

In [6]:
import numpy as np
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Médio

⚫1- Substitua todos os números ímpares em arr com -1 sem alterar arr

In [12]:
import numpy as np
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [11]:
arr = np.arange(10)
out = np.zeros(10)
for i in range(len(arr)):
    if arr[i] % 2 != 0:
        out[i]= -1
    else:
        out[i] = arr[i]
print(arr)
print(out)  

[0 1 2 3 4 5 6 7 8 9]
[ 0. -1.  2. -1.  4. -1.  6. -1.  8. -1.]


⚫2- Converta uma matriz 1D para uma matriz 2D com 2 linhas:

In [7]:
import numpy as np
arr = np.arange(10)
arr.reshape(2, -1) # Setando para “-1” o número de colunas é decidido automáticamente!

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

⚫3- Empilhe matrizes verticalmente:

In [9]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#Método 1
np.concatenate([a, b], axis=0)
#Método 2
np.vstack([a, b])
# Método 3
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

⚫4- Empilhe as matrizes horizontalmente:

In [10]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Método 1
np.concatenate([a, b], axis=1)
# Método 2
np.hstack([a, b])
# Método 3
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

⚫5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.

In [11]:
a = np.array([1,2,3])

In [12]:
import numpy as np
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## Difícil 

⚫1- Calcule as contagens de valores únicos na linha.

In [13]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]


In [14]:
def counts_of_all_values_rowwise(arr2d):
    # Valores exclusivos e suas contagens de linha inteligente
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    # Contagens de todos os valores linha inteligente
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3  4  5  6  7  8  9 10]


C:\Users\Mariana\AppData\Local\Temp\ipykernel_11536\975797783.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]